
backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "champions"
    label: "Champion Reviews"
    folder: "content/champions"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Faction", name: "faction", widget: "string" }
      - { label: "Rarity", name: "rarity", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  - name: "guides"
    label: "Game Guides"
    folder: "content/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
